//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBlib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metier
    {
        public int Identifiant { get; set; }
        public string Libelle { get; set; }
        public string Fiche { get; set; }
        public int IdentifiantDomaine { get; set; }
    
        public virtual Domaine Domaine { get; set; }
    }
}
