//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBlib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postule
    {
        public int Identifiant { get; set; }
        public int IdentifiantOffre { get; set; }
        public int IdentifiantCandidat { get; set; }
    
        public virtual Candidat Candidat { get; set; }
        public virtual Offre Offre { get; set; }
    }
}
